export type QuestBadge = "Featured" | "New drop" | "Ranked";
export type QuestTone = "mint" | "brand" | "sky" | "lavender" | "hero";

export type Quest = {
  id: string;
  title: string;
  mentor: string;
  badge: QuestBadge;
  tone: QuestTone;
  rank: string;
  xp: number;
  stages: number;
  price: string;
  difficulty: string;
  duration: string;
  language: string;
  skills: string[];
  description: string;
};

export const questTones: Record<QuestTone, string> = {
  mint: "bg-primary",
  brand: "bg-brand",
  sky: "bg-secondary",
  lavender: "bg-achievement",
  hero: "bg-hero",
};

export const quests: Quest[] = [
  {
    id: "q-01",
    title: "Launch your first AI product sprint",
    mentor: "Maya Chen",
    badge: "Featured",
    tone: "mint",
    rank: "C",
    xp: 450,
    stages: 8,
    price: "₹799",
    difficulty: "Stage 02",
    duration: "6h 20m",
    language: "English",
    skills: ["Prompts", "MVP", "Shipping"],
    description:
      "Run a one-week sprint from a raw idea to a live demo. You will scope the loop, wire a model, and ship a thin product people can actually click.",
  },
  {
    id: "q-02",
    title: "TypeScript dungeon: types to systems",
    mentor: "Arjun Rao",
    badge: "Ranked",
    tone: "brand",
    rank: "B",
    xp: 620,
    stages: 10,
    price: "₹999",
    difficulty: "Stage 03",
    duration: "8h 10m",
    language: "English",
    skills: ["TypeScript", "Generics", "APIs"],
    description:
      "Climb from everyday types to systems that hold a codebase together. Generics, narrowing, and module boundaries under real pressure.",
  },
  {
    id: "q-03",
    title: "Design systems: ship a living HUD",
    mentor: "Lina Park",
    badge: "New drop",
    tone: "sky",
    rank: "C",
    xp: 380,
    stages: 6,
    price: "₹699",
    difficulty: "Stage 01",
    duration: "5h 05m",
    language: "English",
    skills: ["Tokens", "Components", "Docs"],
    description:
      "Build a HUD kit that other quests can reuse. Tokens, states, and a short spec so the board stays consistent as it grows.",
  },
  {
    id: "q-04",
    title: "Data quest: model, plot, decide",
    mentor: "Noah Idris",
    badge: "Featured",
    tone: "lavender",
    rank: "B",
    xp: 540,
    stages: 9,
    price: "₹899",
    difficulty: "Stage 03",
    duration: "7h 40m",
    language: "English",
    skills: ["SQL", "Charts", "Decisions"],
    description:
      "Turn a messy export into a call you can defend. Clean the set, plot the signal, and write the decision in one page.",
  },
  {
    id: "q-05",
    title: "Public speaking: hold the room",
    mentor: "Sofia Alvarez",
    badge: "Ranked",
    tone: "hero",
    rank: "D",
    xp: 280,
    stages: 5,
    price: "₹499",
    difficulty: "Stage 01",
    duration: "3h 50m",
    language: "English",
    skills: ["Voice", "Stories", "Q&A"],
    description:
      "Learn the beats of a short talk: open, one idea, close. Record, cut, and hold questions without losing the thread.",
  },
  {
    id: "q-06",
    title: "Full-stack raid: API to live map",
    mentor: "Kenji Mori",
    badge: "New drop",
    tone: "mint",
    rank: "A",
    xp: 780,
    stages: 12,
    price: "₹1,299",
    difficulty: "Stage 04",
    duration: "11h 15m",
    language: "English",
    skills: ["APIs", "Auth", "Deploy"],
    description:
      "Stand up auth, a real API, and a live map in one raid. You leave with a deployed quest, not a local demo.",
  },
  {
    id: "q-07",
    title: "Prompt craft: steer the party",
    mentor: "Elena Voss",
    badge: "Featured",
    tone: "sky",
    rank: "C",
    xp: 410,
    stages: 7,
    price: "₹749",
    difficulty: "Stage 02",
    duration: "4h 45m",
    language: "English",
    skills: ["Prompts", "Eval", "Tools"],
    description:
      "Write prompts that hold a task still. Add checks, tool calls, and a small eval set so the party does not wander.",
  },
  {
    id: "q-08",
    title: "SQL vault: query under fire",
    mentor: "Priya Nair",
    badge: "Ranked",
    tone: "brand",
    rank: "B",
    xp: 590,
    stages: 9,
    price: "₹849",
    difficulty: "Stage 03",
    duration: "6h 55m",
    language: "English",
    skills: ["Joins", "Indexes", "Windows"],
    description:
      "Query a live vault with joins, windows, and indexes. Speed matters: you explain the plan, then you beat it.",
  },
  {
    id: "q-09",
    title: "Motion lab: HUD that breathes",
    mentor: "Jonas Hale",
    badge: "New drop",
    tone: "lavender",
    rank: "C",
    xp: 360,
    stages: 6,
    price: "₹649",
    difficulty: "Stage 01",
    duration: "4h 20m",
    language: "English",
    skills: ["Motion", "Timing", "A11y"],
    description:
      "Give the HUD a pulse without noise. Springs, reduced motion, and one slam that makes a stage feel chosen.",
  },
  {
    id: "q-10",
    title: "Security sweep: lock the gates",
    mentor: "Amira Sol",
    badge: "Ranked",
    tone: "hero",
    rank: "A",
    xp: 820,
    stages: 11,
    price: "₹1,199",
    difficulty: "Stage 04",
    duration: "9h 30m",
    language: "English",
    skills: ["Auth", "Threats", "Reviews"],
    description:
      "Walk a product like an attacker. Sessions, secrets, and a review checklist you can run before every drop.",
  },
  {
    id: "q-11",
    title: "Product sense: ship the loop",
    mentor: "Theo Park",
    badge: "Featured",
    tone: "mint",
    rank: "B",
    xp: 500,
    stages: 8,
    price: "₹799",
    difficulty: "Stage 02",
    duration: "5h 50m",
    language: "English",
    skills: ["Discovery", "Metrics", "Scope"],
    description:
      "Pick a loop, cut the rest, and name the metric. You leave with a one-pager a party can actually build.",
  },
  {
    id: "q-12",
    title: "Figma forge: tokens to kit",
    mentor: "Nora Blake",
    badge: "New drop",
    tone: "sky",
    rank: "D",
    xp: 240,
    stages: 5,
    price: "₹449",
    difficulty: "Stage 01",
    duration: "3h 25m",
    language: "English",
    skills: ["Figma", "Auto-layout", "Tokens"],
    description:
      "Forge a small kit from tokens and auto-layout. Components stay square, states stay obvious, handoff stays clean.",
  },
  {
    id: "q-13",
    title: "React raid: server to island",
    mentor: "Chris Adeyemi",
    badge: "Ranked",
    tone: "brand",
    rank: "B",
    xp: 670,
    stages: 10,
    price: "₹999",
    difficulty: "Stage 03",
    duration: "8h 40m",
    language: "English",
    skills: ["RSC", "Caching", "Forms"],
    description:
      "Split a screen into server work and islands. Cache what you can, stream the rest, and keep forms honest.",
  },
  {
    id: "q-14",
    title: "Growth map: find the next wave",
    mentor: "Hana Ito",
    badge: "Featured",
    tone: "lavender",
    rank: "C",
    xp: 430,
    stages: 7,
    price: "₹729",
    difficulty: "Stage 02",
    duration: "5h 15m",
    language: "English",
    skills: ["Funnels", "Copy", "Tests"],
    description:
      "Read a funnel, pick one leak, and run a test. Copy and placement first — no new features until the wave moves.",
  },
  {
    id: "q-15",
    title: "Write to rank: briefs that land",
    mentor: "Marcus Quinn",
    badge: "New drop",
    tone: "hero",
    rank: "D",
    xp: 260,
    stages: 4,
    price: "₹399",
    difficulty: "Stage 01",
    duration: "2h 55m",
    language: "English",
    skills: ["Briefs", "Voice", "Edits"],
    description:
      "Write a brief a builder can start from. One page, one ask, one done definition. Cut until it is sharp.",
  },
  {
    id: "q-16",
    title: "Ops dungeon: ship without drama",
    mentor: "Ravi Mehta",
    badge: "Ranked",
    tone: "mint",
    rank: "A",
    xp: 760,
    stages: 12,
    price: "₹1,149",
    difficulty: "Stage 04",
    duration: "10h 05m",
    language: "English",
    skills: ["CI", "Alerts", "Rollbacks"],
    description:
      "Set the dungeon rules: CI, alerts, and a rollback you trust. Ship on a weekday and sleep that night.",
  },
];
